on:
  push:
    branches:
    - main
    tags:
    - 'v*'

name: Release policy

jobs:

  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-rust.yml@v1
  oidc-token:
    name: Retrieve OIDC token
    permissions:
      # Required by cosign keyless signing
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      token: tokout
    steps:
      - id: step1
        run: |
          echo "$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')"
          echo "::set-output name=token:$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')"

  release:
    needs:
    - test
    - oidc-token
    permissions:
      # Required to push to GHCR
      contents: write
      packages: write
      # Required by cosign keyless signing
      id-token: write
    uses: raulcabello/github-actions/.github/workflows/reusable-release-policy-rust.yml@v1
    with:
      input-wasm: allow_privilege_escalation_psp
      oci-target: ghcr.io/${{ github.repository_owner }}/policies/allow-privilege-escalation-psp
      oidc-token: ${{needs.oidc-token.outputs.token}}
    secrets:
      workflow-pat: ${{ secrets.WORKFLOW_PAT }}
